# Site settings
title: "QUBO Solver Comparison"
description: "Benchmarking Classical vs Quantum Solvers for QUBO Problems"
baseurl: "" # Leave empty for GitHub Pages to serve at root
url: "https://slaue.github.io" # Replace with your GitHub Pages URL

# Theme and Skin
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-remote-theme # Required for using remote themes
  - jekyll-paginate # Pagination for blog posts

# Pagination settings
paginate: 5 # Number of posts per page
paginate_path: "/page:num/"

# Navigation links (Header)
header_pages:
  - index.md
  - about.md

# Author Information
author:
  name: "Your Name"
  avatar: "/assets/images/profile.jpg" # Optional
  bio: "Researcher in classical and quantum computing."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yourusername"

# Footer links (Optional)
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yourusername"

# Defaults for posts and pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
