# Site settings
title: "QUBO Solver Benchmark"
description: "Comparing classical and quantum solvers for QUBO problems."
baseurl: "" 
url: "https://slaue.github.io/qubos_web"
minimal_mistakes_skin: default

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Include pages folder
include:
  - _pages


# Plugins (Only those you need)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache


footer:
  include: custom
  
# Defaults for pages
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
