# Site settings
title: QUBO Solver Benchmark
description: "Comparing classical and quantum solvers for QUBO problems."
github_username: slaue
minimal_mistakes_skin: default

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:title/

# Include pages folder
include:
  - _pages

# Exclude from processing (Optional, if needed)
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (Only those you need)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

# Footer Links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

# Defaults for pages
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
